on: 
  push:
    branches:
      - 24@8.2
name: 🚀 Deploy on push versão 24 PHP 8.2
jobs:
  web-deploy:
    name: 🎉 Deploy v24 PHP 8.2
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files PortalHomolog
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST_PORTALPRODHOMOLOG }}
        username: ${{ secrets.FTP_USERNAME_PORTALHOMOLOG }}
        password: ${{ secrets.FTP_PASSWORD_PORTALPRODHOMOLOG }}
        server-dir: ./homolog/

    - name: 🔗 Call API after deploy PortalHomolog
      run: |
        curl -X POST ${{ secrets.FTP_URL_DBU_HOMOLOG }} \
        -H "Content-Type: application/json" \
        -H "Dbutoken: ${{ secrets.DBU_API_TOKEN }}" \
        -d '{"status": "success", "message": "FTP deploy complete"}'
    
    - name: 📂 Sync files PortalProd
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST_PORTALPRODHOMOLOG }}
        username: ${{ secrets.FTP_USERNAME_PORTALPROD }}
        password: ${{ secrets.FTP_PASSWORD_PORTALPRODHOMOLOG }}
        server-dir: ./

    - name: 🔗 Call API after deploy PortalProd
      run: |
        curl -X POST ${{ secrets.FTP_URL_DBU_PROD }} \
        -H "Content-Type: application/json" \
        -H "Dbutoken: ${{ secrets.DBU_API_TOKEN }}" \
        -d '{"status": "success", "message": "FTP deploy complete"}'
    
    - name: 📂 Sync files 000205 Hlg
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST_PORTALPRODHOMOLOG }}
        username: ${{ secrets.FTP_USERNAME_000205 }}
        password: ${{ secrets.FTP_PASSWORD_000205 }}
        server-dir: ./homolog/

    - name: 🔗 Call API after deploy 000205 Hlg
      run: |
        curl -X POST ${{ secrets.FTP_URL_DBU_000205_HLG }} \
        -H "Content-Type: application/json" \
        -H "Dbutoken: ${{ secrets.DBU_API_TOKEN }}" \
        -d '{"status": "success", "message": "FTP deploy complete"}'

    - name: 📂 Sync files 000205
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST_PORTALPRODHOMOLOG }}
        username: ${{ secrets.FTP_USERNAME_000205 }}
        password: ${{ secrets.FTP_PASSWORD_000205 }}
        server-dir: ./

    - name: 🔗 Call API after deploy 000205
      run: |
        curl -X POST ${{ secrets.FTP_URL_DBU_000205 }} \
        -H "Content-Type: application/json" \
        -H "Dbutoken: ${{ secrets.DBU_API_TOKEN }}" \
        -d '{"status": "success", "message": "FTP deploy complete"}'

    - name: 📂 Sync files 000347 Hlg
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST_PORTALPRODHOMOLOG }}
        username: ${{ secrets.FTP_USERNAME_000347 }}
        password: ${{ secrets.FTP_PASSWORD_000347 }}
        server-dir: ./homolog/

    - name: 🔗 Call API after deploy 000347 Hlg
      run: |
        curl -X POST ${{ secrets.FTP_URL_DBU_000347_HLG }} \
        -H "Content-Type: application/json" \
        -H "Dbutoken: ${{ secrets.DBU_API_TOKEN }}" \
        -d '{"status": "success", "message": "FTP deploy complete"}'

    - name: 📂 Sync files 000347
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST_PORTALPRODHOMOLOG }}
        username: ${{ secrets.FTP_USERNAME_000347 }}
        password: ${{ secrets.FTP_PASSWORD_000347 }}
        server-dir: ./

    - name: 🔗 Call API after deploy 000347
      run: |
        curl -X POST ${{ secrets.FTP_URL_DBU_000347 }} \
        -H "Content-Type: application/json" \
        -H "Dbutoken: ${{ secrets.DBU_API_TOKEN }}" \
        -d '{"status": "success", "message": "FTP deploy complete"}'
        
    - name: 📂 Sync files 000348 Hlg
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST_PORTALPRODHOMOLOG }}
        username: ${{ secrets.FTP_USERNAME_000348 }}
        password: ${{ secrets.FTP_PASSWORD_000348 }}
        server-dir: ./homolog/

    - name: 🔗 Call API after deploy 000348 Hlg
      run: |
        curl -X POST ${{ secrets.FTP_URL_DBU_000348_HLG }} \
        -H "Content-Type: application/json" \
        -H "Dbutoken: ${{ secrets.DBU_API_TOKEN }}" \
        -d '{"status": "success", "message": "FTP deploy complete"}'

    - name: 📂 Sync files 000348
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST_PORTALPRODHOMOLOG }}
        username: ${{ secrets.FTP_USERNAME_000348 }}
        password: ${{ secrets.FTP_PASSWORD_000348 }}
        server-dir: ./

    - name: 🔗 Call API after deploy 000348
      run: |
        curl -X POST ${{ secrets.FTP_URL_DBU_000348 }} \
        -H "Content-Type: application/json" \
        -H "Dbutoken: ${{ secrets.DBU_API_TOKEN }}" \
        -d '{"status": "success", "message": "FTP deploy complete"}'

    - name: 📂 Sync files 000353 Hlg
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST_PORTALPRODHOMOLOG }}
        username: ${{ secrets.FTP_USERNAME_000353 }}
        password: ${{ secrets.FTP_PASSWORD_000353 }}
        server-dir: ./homolog/

    - name: 🔗 Call API after deploy 000353 Hlg
      run: |
        curl -X POST ${{ secrets.FTP_URL_DBU_000353_HLG }} \
        -H "Content-Type: application/json" \
        -H "Dbutoken: ${{ secrets.DBU_API_TOKEN }}" \
        -d '{"status": "success", "message": "FTP deploy complete"}'

    - name: 📂 Sync files 000353
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST_PORTALPRODHOMOLOG }}
        username: ${{ secrets.FTP_USERNAME_000353 }}
        password: ${{ secrets.FTP_PASSWORD_000353 }}
        server-dir: ./

    - name: 🔗 Call API after deploy 000353
      run: |
        curl -X POST ${{ secrets.FTP_URL_DBU_000353 }} \
        -H "Content-Type: application/json" \
        -H "Dbutoken: ${{ secrets.DBU_API_TOKEN }}" \
        -d '{"status": "success", "message": "FTP deploy complete"}'